version: '3.8'

services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    container_name: springboot-container
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/springbootdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres-container
    environment:
      - POSTGRES_DB=springbootdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: